[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[OpenCorePkg]
source = "github"
github = "acidanthera/OpenCorePkg"
use_latest_release = true

[HfsPlus_efi]
source = "github"
github = "acidanthera/OcBinaryData"
path = "Drivers/HfsPlus.efi"

[Lilu]
source = "github"
github = "acidanthera/Lilu"
use_latest_release = true

[VirtualSMC]
source = "github"
github = "acidanthera/VirtualSMC"
use_latest_release = true

[NootedRed]
source = "git"
git = "https://github.com/ChefKissInc/NootedRed.git"
use_commit = true

[SSDT-CPUR_aml]
source = "github"
github = "dortania/Getting-Started-With-ACPI"
path = "extra-files/compiled/SSDT-CPUR.aml"

[SSDT-EC-USBX-DESKTOP_aml]
source = "github"
github = "dortania/Getting-Started-With-ACPI"
path = "extra-files/compiled/SSDT-EC-USBX-DESKTOP.aml"

[USBToolBox]
source = "github"
github = "USBToolBox/kext"
use_latest_release = true

[AppleALC]
source = "github"
github = "acidanthera/AppleALC"
use_latest_release = true

[AMDRyzenCPUPowerManagement]
source = "github"
github = "trulyspinach/SMCAMDProcessor"
use_latest_release = true

[SMCRadeonGPU]
source = "github"
github = "ChefKissInc/RadeonSensor"
use_latest_release = true
